Villa.WebUI/Controllers/FeatureController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Villa.Business.Abstract;
using Villa.Dto.Dtos.FeatureDtos;
using Villa.Entity.Entities;

namespace Villa.WebUI.Controllers
{
    public class FeatureController : Controller
    {
        private readonly IFeatureService _featureService;
        private readonly IMapper _mapper;

        public FeatureController(IFeatureService featureService, IMapper mapper)
        {
            _featureService = featureService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _featureService.TGetListAsync();
            var featureList = _mapper.Map<List<ResultFeatureDto>>(values);
            return View(featureList);
        }

        public async Task<IActionResult> DeleteFeature(ObjectId id)
        {
            await _featureService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateFeature()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateFeature(CreateFeatureDto createFeatureDto)
        {
            var newFeature = _mapper.Map<Feature>(createFeatureDto);
            await _featureService.TCreateAsync(newFeature);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateFeature(ObjectId id)
        {
            var values = await _featureService.TGetByIdAsync(id);
            var updateFeature = _mapper.Map<UpdateFeatureDto>(values);
            return View(updateFeature);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFeature(UpdateFeatureDto updateFeatureDto)
        {
            var Feature = _mapper.Map<Feature>(updateFeatureDto);
            await _featureService.TUpdateAsync(Feature);
            return RedirectToAction("Index");
        }
    }
}

Villa.WebUI/Views/Feature/CreateFeature.cshtml
@model CreateFeatureDto
@{
    ViewData["Title"] = "Yeni Öne Çıkanlar Ekleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <label>Kontrat Türü</label>
    <input type="text" asp-for="Contract" class="form-control" />
    <br />
    <label>Resim Url</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Alt Başlık</label>
    <input type="text" asp-for="SubTitle" class="form-control" />
    <br />
    <label>Metrekare</label>
    <input type="text" asp-for="Square" class="form-control" />
    <br />
    <label>Güvenlik</label>
    <input type="text" asp-for="Safety" class="form-control" />
    <br />
    <button class="btn btn-outline-success">Kaydet</button>
</form>

Villa.WebUI/Views/Feature/Index.cshtml
@model List<ResultFeatureDto>
@{
    ViewData["Title"] = "One Cıkanlar Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-hover table-bordered">
    @{
        int count = 0;
    }
    <tr>
        <th>#</th>
        <th>Fotoğraf Url</th>
        <th>Kontrat Türü</th>
        <th>Başlık</th>
        <th>Alt Başlık</th>
        <th>Güvenlik</th>
        <th>Metrekare</th>
        <th>İşlemler</th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td><img src="@item.ImageUrl" style="height:50px;width:50px" /></td>
            <td>@item.Contract</td>
            <td>@item.Title</td>
            <td>@item.SubTitle</td>
            <td>@item.Safety</td>
            <td>@item.Square</td>
            <td>
                <button onclick="deleteFeature(this)" id="@item.Id" class="btn btn-outline-danger">Sil</button>
                <a asp-controller="Feature" asp-action="UpdateFeature" asp-route-id="@item.Id" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>
    }
</table>

<a asp-controller="Feature" asp-action="CreateFeature" class="btn btn-outline-dark">Yeni Öne Çıkan Bilgisi Ekle</a>


<script>
    function deleteFeature(button) {
        var id = button.getAttribute("id");
        Swal.fire({
            title: 'Silmek istediğinize emin misiniz?',
            text: 'Bu işlemi geri alamazsınız!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Evet, Sil!',
            cancelButtonText: 'İptal'
        }).then((result) => {
            if (result.isConfirmed) {

                window.location.href = "/Feature/DeleteFeature/" + id;

            }
        });

    };

</script>

Villa.WebUI/Views/Feature/UpdateFeature.cshtml
@model UpdateFeatureDto
@{
    ViewData["Title"] = "One Çıkanlar Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="Id" />
    <label>Kontrat Türü</label>
    <input type="text" asp-for="Contract" class="form-control" />
    <br />
    <label>Resim Url</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Alt Başlık</label>
    <input type="text" asp-for="SubTitle" class="form-control" />
    <br />
    <label>Metrekare</label>
    <input type="text" asp-for="Square" class="form-control" />
    <br />
    <label>Güvenlik</label>
    <input type="text" asp-for="Safety" class="form-control" />
    <br />
    <button class="btn btn-outline-success">Kaydet</button>
</form>