Villa.WebUI/Controllers/CounterController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Villa.Business.Abstract;
using Villa.Dto.Dtos.CounterDtos;
using Villa.Entity.Entities;

namespace Villa.WebUI.Controllers
{
    public class CounterController : Controller
    {
        private readonly ICounterService _counterService;
        private readonly IMapper _mapper;
        public CounterController(ICounterService counterService, IMapper mapper)
        {
            _counterService = counterService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _counterService.TGetListAsync();
            var counterList = _mapper.Map<List<ResultCounterDto>>(values);
            return View(counterList);
        }

        public async Task<IActionResult> DeleteCounter(ObjectId id)
        {
            await _counterService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateCounter()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCounter(CreateCounterDto createCounterDto)
        {
            var newCounter = _mapper.Map<Counter>(createCounterDto);
            await _counterService.TCreateAsync(newCounter);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateCounter(ObjectId id)
        {
            var values = await _counterService.TGetByIdAsync(id);
            var updateCounter = _mapper.Map<UpdateCounterDto>(values);
            return View(updateCounter);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCounter(UpdateCounterDto updateCounterDto)
        {
            var counter = _mapper.Map<Counter>(updateCounterDto);
            await _counterService.TUpdateAsync(counter);
            return RedirectToAction("Index");
        }
    }
}

Villa.WebUI/Views/Counter/CreateCounter.cshtml
@model CreateCounterDto
@{
    ViewData["Title"] = "Yeni Sayaç Bilgisi Ekleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Sayaç</label>
    <input type="text" asp-for="Count" class="form-control" />
    <br />
    <button class="btn btn-outline-success">Kaydet</button>
</form>

Villa.WebUI/Views/Counter/Index.cshtml
@model List<ResultCounterDto>
@{
    ViewData["Title"] = "Sayaç Bilgileri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-hover table-bordered">
    @{
        int count = 0;
    }
    <tr>
        <th>#</th>
        <th>Başlık</th>
        <th>Sayaç</th>
        <th>İşlemler</th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.Title</td>
            <td>@item.Count</td>
            <td>
                <a asp-controller="Counter" asp-action="DeleteCounter" asp-route-id="@item.Id" class="btn btn-outline-danger">Sil</a>
                <a asp-controller="Counter" asp-action="UpdateCounter" asp-route-id="@item.Id" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>
    }
</table>

<a asp-controller="Counter" asp-action="CreateCounter" class="btn btn-outline-dark">Yeni Sayaç Bilgisi Ekle</a>

Villa.WebUI/Views/Counter/UpdateCounter.cshtml
@model UpdateCounterDto
@{
    ViewData["Title"] = "Sayaç Bilgisi Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="Id" />
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Sayaç</label>
    <input type="text" asp-for="Count" class="form-control" />
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
</form>